# MineShell Configuration
version: "1.0.0"

# Server Configuration
server:
  backend:
    port: 3000
    host: "0.0.0.0"  # Change to your domain or IP for production
  frontend:
    port: 8080
    host: "0.0.0.0"  # Change to your domain or IP for production

# API Configuration
api:
  base_url: "http://localhost:3000"  # Change to your domain or IP for production
  ws_url: "ws://localhost:3000"      # Change to your domain or IP for production

# Minecraft Server Defaults
minecraft:
  default_port: 25565
  min_ram: "1G"
  max_ram: "2G"

# Admin Configuration
admin:
  username: "admin"
  password: "mineshell123"  # Change this in production!

# JWT Configuration
jwt_secret: "your-secret-key-here"  # Change this in production! 